# Generated by Django 5.1.6 on 2025-02-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_certificate_general_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='study_center',
        ),
    ]
