# Generated by Django 5.1.6 on 2025-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=10),
        ),
    ]
