# Generated by Django 5.1.6 on 2025-02-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_generalset_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSet',
            new_name='CertificatesSet',
        ),
    ]
