# Generated by Django 5.1.6 on 2025-02-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_certificatesset_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='general_set',
            new_name='certificate_set',
        ),
    ]
