# Generated by Django 5.1.6 on 2025-02-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_general_set_certificate_certificate_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_set',
            new_name='certificates_set',
        ),
    ]
