# Generated by Django 5.1.6 on 2025-02-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_certificate_set_certificate_certificates_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='study_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='app.studycenter'),
        ),
    ]
