# Generated by Django 5.1.6 on 2025-03-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_study_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='finished_date_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='id_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='qr_code_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
