# Generated by Django 5.1.6 on 2025-03-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_finished_date_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
