# Generated by Django 5.1.6 on 2025-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='UUID',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
