# Generated by Django 5.1.6 on 2025-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_certificate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='UUID',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
