# Generated by Django 5.1.6 on 2025-03-05 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_certificate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
