# Generated by Django 5.1.6 on 2025-03-05 14:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_certificate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='UUID',
            field=models.CharField(default=app.models.generate_short_uuid, editable=False, max_length=7, unique=True),
        ),
    ]
