# Generated by Django 5.1.6 on 2025-03-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_certificate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='social_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SocialStatus',
        ),
    ]
